Nitzan/eco 199/native spend2 (#67)
* updated the TypeORM package
the new version (@next) supports single table inheritance

* refactored Order
now there's the base (abstract) Order model class, and the MarketplaceOrder model subclass

* use Order.setStatus instead of changing it directly

* moved createMarketplaceOrder to routes/orders

* moved jwt related logic into a new jwt ts file

* the ExternalOrder

* updating external order with confirmation

* tthree PR comment fixes

* remove meta.wallet_address and use blockchain_data instead

* no more 'single table inheritance

* fixed a bug in createExternalOrder

* reverted the TypeORM version change

* fixed import error

* add a orders unittest

* fixed order models inheritance bug

* fixed order models inheritance bug

* add 2 tests and make whole thing compile

* add payment complete mock

* fixed compilation error
this error:
tests/src/helpers.ts(38,40): error TS2339: Property 'new' does not exist on type '{ new (data?: DeepPartial<Order>): Order; ORIGIN: string; count(offerId: string, userId?: string)...'.

was do to how the compiler outputs the definition for `MarketplaceOrder`:
```
declare const MarketplaceOrder: {
    new(data?: Partial<Order> | undefined): Order;
    ...
```
this format tells the compiler that `MarketplaceOrder` is a constructor (should be used with `new MarketplaceOrder`).
Seems that wrapping new with quotes worked.

* fix tests